use_frameworks!

target 'AwesomeImage_Example' do
  pod 'AwesomeImage', :path => '../'
  pod 'AwesomeLoading', git: 'https://github.com/iOSWizards/AwesomeLoading', tag: '0.1.5'

  target 'AwesomeImage_Tests' do
    inherit! :search_paths

    
  end
end
